[program:costage-public]
environment=PROC_NAME="costage-public"
command=/opt/supervisor-scripts/costage-public.sh
autostart=true
autorestart=unexpected
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
