[program:costage-https]
environment=PROC_NAME="costage-https"
command=/opt/supervisor-scripts/costage-https.sh
autostart=true
autorestart=unexpected
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
