[program:costage]
directory=/costage
environment=PROC_NAME="costage"
command=/opt/supervisor-scripts/costage.sh
autostart=true
autorestart=unexpected
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
